name: Flask CI testing

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.9
      - name: make venv
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: install requirements
        run: |
          pip install -r requirements.txt
      - name: check if workflow working
        run:
          echo "Python version $(python-version)"
          echo "work dir $(pwd)"
      - name: run tests
          run: pytest
